layout_spectrum: 0.4551971
typography_spectrum: 0.6469534
color:
  saturation: 0.8591931
  lightness: 0.07950389
  brandStrength: 0.176273
  rhythmicContrast: 0.8836635
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Test-Rollo
