collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6469534
color:
  saturation: 0.7493734
  brandStrength: 0.325188
  lightness: 0.1929825
  brandColors:
    - '#4E82B1'
    - '#DCD9C8'
    - '#B2A389'
    - '#27343A'
    - '#000000'
  rhythmicContrast: 0.8659148
layout_spectrum: 0.4185464
name: Test-Rollo
